name_to_unit = {
    # Table 1
    "Latitude": "[decimal degrees]",
    "Longitude": "[decimal degrees]",
    "Depth_bottom": "[m]",
    "CTDPRES": "[dbar]",
    "Depth": "[m]",
    "CTDTEMP_ITS90": "[deg_C]",
    "CTDOXY": "[umol/kg]",
    "Oxygen": "[umol/kg]",
    "DIC": "[umol/kg]",
    "TA": "[umol/kg]",
    "TEMP_pH": "[deg_C]",
    "TEMP_Carbonate": "[deg_C]",
    "TEMP_fCO2": "[dec_C]",
    "Silicate": "[umol/kg]",
    "Phosphate": "[umol/kg]",
    "Nitrate": "[umol/kg]",
    "Nitrite": "[umol/kg]",
    "Nitrate_and_Nitrite": "[umol/kg]",
    "Ammonium": "[umol/kg]",
    "Chl_a": "[ug/kg]",
    "Chl_a (sensor)": "[ug/kg]",
    "DOC": "[umol/kg]",
    "Delta_C13_DIC": "[per mill]",
    "Delta_C14_DIC": "[per mill]",
    "Delta_C14_DIC_error": "[per mill]",
    "CFC11": "[pmol/kg]",
    "CFC12": "[pmol/kg]",
    "CFC113": "[pmol/kg]",
    "SF6": "[fmol/kg]",
    "N2O": "[nmol/kg]",
    # Supplementary Table 1
    "PAR": "[umol/m2/s]",
    "CDOM": "[1/m]",
    "POC": "[umol/kg]",
    "TOC": "[umol/kg]",
    "PIC": "[umol/kg]",
    "DON": "[umol/kg]",
    "PON": "[ug/kg]",
    "TON": "[umol/kg]",
    "TDN": "[umol/kg]",
    "DOP": "[umol/kg]",
    "Delta_C14_DOC": "[per mill]",
    "Delta_C14_DOC_error": "[per mill]",
    "Delta_C14_TOC": "[per mill]",
    "Delta_C14_TOC_error": "[per mill]",
    "Delta_O18": "[per mill]",
    "Delta_O18_error": "[per mill]",
    "Delta_N15_Nitrate": "[per mill]",
    "Delta_N15_Nitrate_error": "[per mill]",
    "Tritium": "[TU]",
    "Tritium_error": "[TU]",
    "Delta_He3": "[%]",
    "Delta_He3_error": "[%]",
    "CH4": "[nmol/kg]",
    "CH3Cl": "[pmol/kg]",
    "CCl4": "[pmol/kg]",
    "Helium": "[nmol/kg]",
    "Helium_error": "[nmol/kg]",
    "Neon": "[nmol/kg]",
    "Neon_error": "[nmol/kg]",
    "Argon": "[umol/kg]",
    "DMS": "[nmol/kg]",
    "Methyl_Chloroform": "[pmol/kg]",
    "Iodate": "[nmol/kg]",
    "Iodide": "[nmol/kg]",
    "Krypton_85": "[dpm/1000kg]",
    "Cesium_137": "[dpm/100kg]",
    "Radium_226": "[dpm/100kg]",
    "Radium_228": "[dpm/100kg]",
    "Strontium_90": "[dpm/100kg]",
    "Aluminium": "[nmol/kg]",
    "Barium": "[nmol/kg]",
    "Calcium": "[umol/kg]",
    "Copper": "[nmol/kg]",
    "Iron": "[nmol/kg]",
    "Manganese": "[nmol/kg]",
    "Nickel": "[nmol/kg]",
}

name_to_dp = {
    # Table 1
    "Year_UTC": 0,
    "Month_UTC": 0,
    "Day_UTC": 0,
    "Yearday_UTC": 2,
    "Latitude": 4,
    "Longitude": 4,
    "Depth_bottom": 0,
    "CTDPRES": 1,
    "Depth": 1,
    "CTDTEMP_ITS90": 3,
    "CTDSAL_PSS78": 3,
    "CTDOXY": 1,
    "Oxygen": 1,
    "DIC": 1,
    "TA": 1,
    "pH_TS_measured": 4,
    "pH_SWS_measured": 4,
    "pH_FS_measured": 4,
    "pH_NBS_measured": 4,
    "pH_TS_measured (electrode)": 4,
    "pH_SWS_measured (electrode)": 4,
    "pH_FS_measured (electrode)": 4,
    "pH_NBS_measured (electrode)": 4,
    "TEMP_pH": 2,
    "Carbonate_measured": 1,
    "TEMP_Carbonate": 2,
    "fCO2_measured": 1,
    "TEMP_fCO2": 2,
    "Silicate": 2,
    "Phosphate": 2,
    "Nitrate": 2,
    "Nitrite": 2,
    "Nitrate_and_Nitrite": 2,
    "Ammonium": 2,
    "Chl_a": 3,
    "Chl_a (sensor)": 3,
    "DOC": 2,
    "Delta_C13_DIC": 2,
    "Delta_C14_DIC": 2,
    "Delta_C14_DIC_error": 2,
    "CFC11": 3,
    "CFC12": 3,
    "CFC113": 3,
    "SF6": 3,
    "N2O": 2,
}
